### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by Nerzal** [OgreTransporter/fritzing-parts-extra#1]
Hi, first of all thank you very much for the fritzing parts! 
I'd like to use the Capacitive Soil Moisture Sensor in a book, which i'm currently writing. 

But i cannot use an image (or an image of a fritzing part) from this repository without your permission. 
I'd happily give credits for the source of the fritzing part :) 

So could you add some kind of open source license, or grant me the permission to use the part?

**Comment by OgreTransporter** [comment]
Thanks for the tip! I have placed the files under the GPL v3 and added a corresponding license file.

**Comment by Nerzal** [comment]
Thank u very much! <3
